FROM node:alpine

WORKDIR /app/backend

COPY /package*.json /app/backend
COPY ./yarn.lock /app/backend
COPY tsconfig.json /app/backend
COPY . /app/backend

RUN npm install

EXPOSE 3001

CMD npm run dev